# Generated by Django 6.0.7 on 2026-07-20 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacefolder',
            name='icon',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
