# Generated by Django 6.0.7 on 2026-07-20 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_workspacefolder_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacefolder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
