# Generated by Django 6.0.7 on 2026-07-21 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_workspacemessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_message', models.TextField()),
                ('summary', models.TextField(blank=True)),
                ('facts_before', models.JSONField(blank=True, default=dict)),
                ('facts_after', models.JSONField(blank=True, default=dict)),
                ('sections_before', models.JSONField(blank=True, default=dict)),
                ('sections_after', models.JSONField(blank=True, default=dict)),
                ('tasks_before', models.JSONField(blank=True, default=list)),
                ('tasks_after', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='projects.project')),
            ],
        ),
    ]
