# Generated by Django 6.0.7 on 2026-07-22 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_projectchange'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectHealthReviewRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('health_score', models.PositiveSmallIntegerField()),
                ('critical_issues', models.JSONField(blank=True, default=list)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('strengths', models.JSONField(blank=True, default=list)),
                ('summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_reviews', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
