# Generated by Django 6.0.7 on 2026-07-22 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_projecthealthreviewrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectConflict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('warning', 'Warning'), ('critical', 'Critical')], max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved'), ('ignored', 'Ignored')], default='open', max_length=20)),
                ('source_type', models.CharField(blank=True, max_length=50)),
                ('source_reference', models.CharField(blank=True, max_length=255)),
                ('suggested_fix', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts', to='projects.project')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts', to='projects.projecthealthreviewrecord')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
