# Generated by Django 6.0.7 on 2026-07-22 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_projectconflict'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectconflict',
            name='key',
            field=models.CharField(db_index=True, default='legacy_conflict', max_length=100),
            preserve_default=False,
        ),
    ]
