# Generated by Django 6.0.7 on 2026-07-23 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_projectconflict_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('project_created', 'Project Created'), ('workspace_generated', 'Workspace Generated'), ('workspace_updated', 'Workspace Updated'), ('project_reviewed', 'Project Reviewed'), ('conflict_fixed', 'Conflict Fixed'), ('conflict_resolved', 'Conflict Resolved'), ('conflict_ignored', 'Conflict Ignored'), ('change_undone', 'Change Undone'), ('task_completed', 'Task Completed'), ('task_reopened', 'Task Reopened')], max_length=40)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
