# Generated by Django 6.0.7 on 2026-07-23 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='dependencies',
            field=models.ManyToManyField(blank=True, related_name='dependents', to='projects.task'),
        ),
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='estimated_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectevent',
            name='event_type',
            field=models.CharField(choices=[('project_created', 'Project Created'), ('workspace_generated', 'Workspace Generated'), ('workspace_updated', 'Workspace Updated'), ('project_reviewed', 'Project Reviewed'), ('conflict_fixed', 'Conflict Fixed'), ('conflict_resolved', 'Conflict Resolved'), ('conflict_ignored', 'Conflict Ignored'), ('change_undone', 'Change Undone'), ('task_completed', 'Task Completed'), ('task_reopened', 'Task Reopened'), ('task_status_changed', 'Task Status Changed')], max_length=40),
        ),
    ]
