# Generated by Django 6.0.7 on 2026-07-23 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_projectmilestone'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='milestone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='projects.projectmilestone'),
        ),
        migrations.AlterField(
            model_name='projectevent',
            name='event_type',
            field=models.CharField(choices=[('project_created', 'Project Created'), ('workspace_generated', 'Workspace Generated'), ('workspace_updated', 'Workspace Updated'), ('project_reviewed', 'Project Reviewed'), ('conflict_fixed', 'Conflict Fixed'), ('conflict_resolved', 'Conflict Resolved'), ('conflict_ignored', 'Conflict Ignored'), ('change_undone', 'Change Undone'), ('task_completed', 'Task Completed'), ('task_reopened', 'Task Reopened'), ('task_status_changed', 'Task Status Changed'), ('task_dependencies_changed', 'Task Dependencies Changed')], max_length=40),
        ),
    ]
