# Generated by Django 6.0.7 on 2026-07-24 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_alter_projectevent_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='schedule_last_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='schedule_needs_refresh',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='schedule_refresh_reason',
            field=models.TextField(blank=True),
        ),
    ]
