# Generated by Django 6.0.7 on 2026-07-24 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_project_schedule_last_generated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('generating', 'Generating'), ('active', 'Active'), ('archived', 'Archived')], default='draft', max_length=20),
        ),
    ]
