# Generated by Django 6.0.7 on 2026-07-31 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_budgetitem_projectresource'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetitem',
            name='actual_unit_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='budgetitem',
            name='alternative_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='budgetitem',
            name='confidence',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='budgetitem',
            name='is_physical_part',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='budgetitem',
            name='purchase_status',
            field=models.CharField(choices=[('planned', 'Planned'), ('ordered', 'Ordered'), ('purchased', 'Purchased'), ('skipped', 'Skipped')], default='planned', max_length=20),
        ),
        migrations.AddField(
            model_name='budgetitem',
            name='requirement_level',
            field=models.CharField(choices=[('required', 'Required'), ('recommended', 'Recommended'), ('optional', 'Optional')], default='required', max_length=20),
        ),
        migrations.AddField(
            model_name='budgetitem',
            name='source_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='budgetitem',
            name='category',
            field=models.CharField(choices=[('hardware', 'Hardware'), ('electronics', 'Electronics'), ('mechanical', 'Mechanical'), ('software', 'Software'), ('api', 'API'), ('hosting', 'Hosting'), ('design', 'Design'), ('marketing', 'Marketing'), ('labor', 'Labor'), ('other', 'Other')], default='other', max_length=30),
        ),
    ]
