# Generated by Django 6.0.7 on 2026-07-31 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_budgetitem_actual_unit_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectresource',
            name='reason_needed',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='projectresource',
            name='related_task',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='projectresource',
            name='topic',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='projectresource',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
