# Generated by Django 6.0.7 on 2026-08-05 01:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_projectresource_reason_needed_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_project_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectevent',
            name='event_type',
            field=models.CharField(choices=[('project_created', 'Project Created'), ('workspace_generated', 'Workspace Generated'), ('workspace_updated', 'Workspace Updated'), ('project_reviewed', 'Project Reviewed'), ('conflict_fixed', 'Conflict Fixed'), ('conflict_resolved', 'Conflict Resolved'), ('conflict_ignored', 'Conflict Ignored'), ('change_undone', 'Change Undone'), ('task_completed', 'Task Completed'), ('task_reopened', 'Task Reopened'), ('task_status_changed', 'Task Status Changed'), ('task_dependencies_changed', 'Task Dependencies Changed'), ('schedule_generated', 'Schedule Generated'), ('member_added', 'Member Added'), ('member_removed', 'Member Removed'), ('member_role_changed', 'Member Role Changed')], max_length=40),
        ),
    ]
