# Generated by Django 6.0.7 on 2026-08-08 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_projectmembership_role_notes_alter_task_assignee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubRepository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installation_id', models.BigIntegerField()),
                ('repository_id', models.BigIntegerField(unique=True)),
                ('owner', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('html_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='github_repository', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='GitHubIssueLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_id', models.BigIntegerField(unique=True)),
                ('issue_number', models.PositiveIntegerField()),
                ('issue_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='github_issue_link', to='projects.task')),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_links', to='projects.githubrepository')),
            ],
        ),
    ]
