# Generated by Django 6.0.7 on 2026-08-12 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0025_githubrepository_githubissuelink'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('suggestion', 'Suggestion'), ('bug', 'Bug Report'), ('feature', 'Feature Request'), ('other', 'Other')], default='suggestion', max_length=20)),
                ('title', models.CharField(max_length=180)),
                ('message', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Nice to have'), ('medium', 'Important'), ('high', 'Very important')], default='medium', max_length=20)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('page_url', models.URLField(blank=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_submissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
