# Generated by Django 6.0.7 on 2026-09-08 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0028_rename_user_notification_recipient_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentRunEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=30)),
                ('tool_name', models.CharField(blank=True, max_length=50)),
                ('data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='projects.agentrun')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
