# Generated by Django 6.0.7 on 2026-09-12 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0029_agentrunevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentrun',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('blocked', 'Blocked'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=20),
        ),
    ]
