# Generated by Django 6.0.7 on 2026-09-12 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0032_connectedaccount_delete_githubconnection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubrepository',
            name='default_branch',
            field=models.CharField(default='main', max_length=255),
        ),
        migrations.AlterField(
            model_name='githubrepository',
            name='installation_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
