# Generated by Django 6.0.7 on 2026-09-18 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0033_githubrepository_default_branch_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentWorkspaceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('preserved', 'Preserved'), ('deleted', 'Deleted')], default='active', max_length=20)),
                ('workspace_path', models.TextField(blank=True)),
                ('repository_owner', models.CharField(blank=True, max_length=255)),
                ('repository_name', models.CharField(blank=True, max_length=255)),
                ('repository_branch', models.CharField(blank=True, max_length=255)),
                ('base_commit_sha', models.CharField(blank=True, max_length=64)),
                ('last_synced_commit_sha', models.CharField(blank=True, max_length=64)),
                ('manifest', models.JSONField(blank=True, default=dict)),
                ('patch', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('preserved_at', models.DateTimeField(blank=True, null=True)),
                ('run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_record', to='projects.agentrun')),
            ],
        ),
    ]
