# Generated by Django 6.0.7 on 2026-09-19 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0034_agentworkspacerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentrun',
            name='resumed_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resumed_runs', to='projects.agentrun'),
        ),
    ]
