# Generated by Django 6.0.7 on 2026-09-20 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0036_agentapprovalrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentapprovalrequest',
            name='continuation_run',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='continued_approval', to='projects.agentrun'),
        ),
    ]
