# Generated by Django 6.0.7 on 2026-09-20 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0037_agentapprovalrequest_continuation_run'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentapprovalrequest',
            name='consumed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
