# Generated by Django 6.0.7 on 2026-09-21 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0038_agentapprovalrequest_consumed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentworkspacerecord',
            name='workspace_snapshot',
            field=models.FileField(blank=True, upload_to='agent_workspace_snapshots/'),
        ),
        migrations.AddField(
            model_name='agentworkspacerecord',
            name='workspace_snapshot_manifest',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
