# Generated by Django 6.0.7 on 2026-09-23 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0040_agentrun_result_actions_agentrun_result_files_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentrun',
            name='model_name',
            field=models.CharField(default='gpt-5.6-sol', max_length=100),
        ),
    ]
